### ISSUE TITLE
Failed to parse "F | T | F"

### ISSUE THREAD

**Issue by dvtomas** [Canop/bet#2]
I ran into some weird problems when parsing > 2 *top-level* atoms connected with binary operators. . The minimum reproducible example is to add the following checks to `test_bool()` in `test_bool.rs`:

```
    check("F | F | F", false); // Only possible to evaluate after the line (Self::Or, None) => a is added to BoolOperator::eval
    check("F | T | F", true); // Fails! The middle T is not part of the expression tree!
```

The first line is only possible to evaluate when `BoolOperator::eval` is modified like this:

```
    fn eval(self, a: bool, b: Option<bool>) -> bool {
        match (self, b) {
            (Self::And, Some(b)) => a & b,
            (Self::Or, Some(b)) => a | b,
            (Self::Not, None) => !a,
            (Self::Or, None) => a, // Had to add this line
            _ => unreachable!("{} {:?} {:?}", a, self, b),
        }
    }
```

Even then, the resulting expression tree is not correct, `F | T | F` evaluates to `false`. When I keep adding the `|`s, only the leftmost and rightmost atoms remain in the resulting expression tree.

**Comment by Canop** [comment]
Thanks for finding this. I'll push a fix.

**Comment by Canop** [comment]
If you see things still failing, or tests to add, please tell.
If not, I should release a new version soon.

**Comment by dvtomas** [comment]
Thank you so much for the fix. I don't have any specific test cases to add. If you want to be really thorough, you might consider using a property based testing, e.g. something like this: https://chatgpt.com/share/99a12c41-b102-4b63-b82b-040752150ceb
